name: agri
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.2
  flutter_secure_storage: ^9.0.0
  google_fonts: ^6.2.1
  animate_do: ^3.2.0
  image_picker: ^1.0.7 
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  http_parser: ^4.0.2
  intl: ^0.18.0
  firebase_core: ^2.25.0
  cloud_firestore: ^4.15.0   
  firebase_database: ^10.4.0
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/rice.jpg
    - assets/images/beans.jpg
    - assets/images/tomatoes.jpg
    - assets/images/corn.jpg
    - assets/logo.png